stages:
  - deploy

deploy_site:
  stage: deploy
  image: node:latest
  script:
    - npm install -g appwrite-cli
    
    # Login
    - appwrite client --endpoint https://cloud.appwrite.io/v1 --project-id 69f4d43e001852db5970 --key $APPWRITE_API_KEY
    
    # Use --all to skip the manual selection question
    - appwrite push site --all
  only:
    - main
