stages:
  - deploy

deploy_site:
  stage: deploy
  image: node:latest
  script:
    - npm install -g appwrite-cli
    
    # 1. Login
    - appwrite client --endpoint https://cloud.appwrite.io/v1 --project-id 69f4d43e001852db5970 --key $APPWRITE_API_KEY
    
    # 2. Create the file using a single-line echo to prevent GitLab collapsing it
    - echo '{"projectId":"69f4d43e001852db5970","sites":[{"$id":"69f4e17f00049568c8df","name":"My Site","root":"./","commands":"echo build_skipped","output":"./"}]}' > appwrite.json

    # 3. Use 'all' and 'force' to push
    - appwrite push site --all --force
  only:
    - main
